# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition for shared filesystem writer

version: '1'

name: shared-filesystem-writer
binaries:
  - path: build/shared-filesystem-writer.wasm

config:
  environment:
    - Message
  permissions:
    - console
