# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: filesystem
binaries:
  - path: build/filesystem.wasm

config:
  environment:
    - Message
  permissions:
    - console