# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition for shared filesystem reader

version: '1'

name: shared-filesystem-reader
binaries:
  - path: build/shared-filesystem-reader.wasm

config:
  environment:
    - Message
  permissions:
    - console