# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: blinky-xmas
binaries:
  - path: build/blinky-xmas.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - ocre_timers
    - ocre_gpio
