# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: sensor-imu
binaries:
  - path: build/sensor-imu.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - ocre_gpio
    - ocre_timers
    - ocre_sensors
