# Copyright (C) 2024 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: subscriber_temp
binaries:
  - path: build/subscriber_temp.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - ocre_timers
    - ocre_messaging