# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: blinky-u585
binaries:
  - path: build/blinky-u585.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - networking
    - ocre_timers
    - ocre_gpio
