# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: blinky-board-generic
binaries:
  - path: build/blinky-board-generic.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - ocre_timers
    - ocre_gpio
