# Copyright (C) 2024 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: echo
binaries:
  - path: build/echo.wasm

config:
  environment:
    - ENABLED=true
  permissions:
    - network
  