# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: blinky-button
binaries:
  - path: build/blinky-button.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - networking
    - ocre_gpio
    - ocre_timers
