# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: filesystem-full
binaries:
  - path: build/filesystem-full.wasm

config:
  environment:
    - Message
  permissions:
    - console
