# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: modbus-server-u585
binaries:
  - path: build/modbus-server.wasm

config:
  permissions:
    - networking
    - ocre_sensors
    - ocre_gpio
    - ocre_timers