# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: modbus-client
binaries:
  - path: build/modbus-client.wasm

config:
  permissions:
    - networking