# Copyright (C) 2024 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: publisher_1

binaries:
  - path: build/publisher_1.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - ocre_timers
    - ocre_messaging